export const antigravityPresets = {
  subtle: {
    count: 200,
    magnetRadius: 5,
    ringRadius: 6,
    waveSpeed: 0.25,
    waveAmplitude: 0.7,
    particleSize: 1.2,
    lerpSpeed: 0.04,
    color: '#A3B8FF',
    autoAnimate: true,
    particleVariance: 0.6,
    rotationSpeed: 0.1,
    depthFactor: 0.8,
    pulseSpeed: 2,
    particleShape: 'sphere',
    fieldStrength: 12,
  },
  hero: {
    count: 350,
    magnetRadius: 7,
    ringRadius: 8,
    waveSpeed: 0.5,
    waveAmplitude: 1.3,
    particleSize: 1.7,
    lerpSpeed: 0.07,
    color: '#FF9FFC',
    autoAnimate: true,
    particleVariance: 1.2,
    rotationSpeed: 0.25,
    depthFactor: 1.3,
    pulseSpeed: 3.5,
    particleShape: 'capsule',
    fieldStrength: 8,
  },
  neon: {
    count: 300,
    magnetRadius: 6,
    ringRadius: 7,
    waveSpeed: 0.45,
    waveAmplitude: 1,
    particleSize: 1.4,
    lerpSpeed: 0.06,
    color: '#00F5FF',
    autoAnimate: true,
    particleVariance: 1,
    rotationSpeed: 0.2,
    depthFactor: 1.1,
    pulseSpeed: 3,
    particleShape: 'tetrahedron',
    fieldStrength: 10,
  },
  minimal: {
    count: 120,
    magnetRadius: 4,
    ringRadius: 5,
    waveSpeed: 0.2,
    waveAmplitude: 0.5,
    particleSize: 0.9,
    lerpSpeed: 0.035,
    color: '#FFFFFF',
    autoAnimate: true,
    particleVariance: 0.4,
    rotationSpeed: 0.08,
    depthFactor: 0.7,
    pulseSpeed: 1.8,
    particleShape: 'sphere',
    fieldStrength: 14,
  },
  crazy: {
    count: 450,
    magnetRadius: 9,
    ringRadius: 10,
    waveSpeed: 0.8,
    waveAmplitude: 1.8,
    particleSize: 1.9,
    lerpSpeed: 0.09,
    color: '#FF4B91',
    autoAnimate: true,
    particleVariance: 1.5,
    rotationSpeed: 0.4,
    depthFactor: 1.6,
    pulseSpeed: 4.2,
    particleShape: 'box',
    fieldStrength: 7,
  },
  loader: {
    count: 180,
    magnetRadius: 5.5,
    ringRadius: 4.5,
    waveSpeed: 0.55,
    waveAmplitude: 1.1,
    particleSize: 1.1,
    lerpSpeed: 0.08,
    color: '#7C3AED',
    autoAnimate: true,
    particleVariance: 0.9,
    rotationSpeed: 0.3,
    depthFactor: 1.2,
    pulseSpeed: 3,
    particleShape: 'capsule',
    fieldStrength: 9,
  },
};


